baseURL = "/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Algorithm Scripting"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

[params]
title = "Algorithm Scripting"
author = "Algorithm Scripting"
description = "Solving programming problems."
profilePicture = "images/profile.jpg"
keywords = ""
favicon = "favicons/"
customCss = []
customJs = []
mainSections = ["post"]
images = ["images/site-feature-image.png"]

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-twitter"
title = "twitter"
url = "https://twitter.com/AkosuaAkimbo"

[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/stella-dare-2323b9b2/"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/stel-dare"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:stelladare2@gmail.com.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "All Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"